# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlankReactNativeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BlankReactNativeProject
  pod 'Google-Mobile-Ads-SDK'
  #target 'BlankReactNativeProject-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'BlankReactNativeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BlankReactNativeProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BlankReactNativeProject-tvOS

  target 'BlankReactNativeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
